#
# Copyright (c) Microsoft Corporation. Licensed under the MIT License.
#

# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: 'kaizimmerm_twins-java-client'
      organization: 'kaizimmerm-github'
      scannerMode: Other
      extraProperties: |
        sonar.exclusions=azure-digital-twins-java-client/src/main/java/com/microsoft/twins/model/**
  - task: Maven@3
    inputs:
      mavenPomFile: "pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      sonarQubeRunAnalysis: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "package"
  - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'
